import { z } from "zod";

// Course info schema - generated by info agent
export const courseInfoSchema = z.object({
    title: z
        .string()
        .describe("Short, catchy title for the course (1-5 words)"),
    description: z
        .string()
        .describe("Brief overview of the course (1-2 sentences)"),
    imageQuery: z
        .string()
        .describe("Search query to find a relevant cover image"),
});

export type CourseInfo = z.infer<typeof courseInfoSchema>;

// Chapter schema - used by planner agent
export const chapterSchema = z.object({
    caption: z.string().describe("Short chapter title (1-5 words)"),
    content: z
        .array(z.string())
        .describe(
            "Specific learning points as bullet points (3-6 items per chapter)",
        ),
    timeMinutes: z
        .number()
        .int()
        .positive()
        .describe("Estimated time for the chapter in minutes"),
    note: z
        .string()
        .optional()
        .describe("Optional context or prerequisites for the explainer agent"),
});

export type Chapter = z.infer<typeof chapterSchema>;

// Learning path schema - output from planner agent
export const learningPathSchema = z.object({
    chapters: z
        .array(chapterSchema)
        .min(1)
        .describe("List of chapters for the learning path"),
});

export type LearningPath = z.infer<typeof learningPathSchema>;

// Chapter content schema - output from explainer agent (JSX format)
export const chapterContentSchema = z.object({
    jsxCode: z
        .string()
        .describe(
            "The JSX component code for the chapter, starting with () => { and ending with }",
        ),
    keyTakeaways: z
        .array(z.string())
        .describe("Key points the learner should remember from this chapter"),
});

export type ChapterContent = z.infer<typeof chapterContentSchema>;

// Legacy content schema for backwards compatibility
export const legacyChapterContentSchema = z.object({
    content: z.string().describe("Markdown content (legacy)"),
    keyTakeaways: z.array(z.string()),
});

export type LegacyChapterContent = z.infer<typeof legacyChapterContentSchema>;

// Multiple choice question schema
export const mcQuestionSchema = z.object({
    type: z.literal("multiple_choice"),
    question: z.string().describe("The question text"),
    answerA: z.string().describe("Answer option A"),
    answerB: z.string().describe("Answer option B"),
    answerC: z.string().describe("Answer option C"),
    answerD: z.string().describe("Answer option D"),
    correctAnswer: z
        .enum(["a", "b", "c", "d"])
        .describe("The letter of the correct answer"),
    explanation: z.string().describe("Why the correct answer is correct"),
});

export type MCQuestion = z.infer<typeof mcQuestionSchema>;

// Open text question schema
export const openTextQuestionSchema = z.object({
    type: z.literal("open_text"),
    question: z.string().describe("The question text"),
    correctAnswer: z.string().describe("The expected correct answer"),
    gradingCriteria: z
        .string()
        .optional()
        .describe("Criteria for grading the answer"),
});

export type OpenTextQuestion = z.infer<typeof openTextQuestionSchema>;

// Quiz schema - output from quiz agent
export const quizSchema = z.object({
    questions: z
        .array(z.union([mcQuestionSchema, openTextQuestionSchema]))
        .min(3)
        .max(15)
        .describe("Mix of multiple choice and open text questions"),
});

export type Quiz = z.infer<typeof quizSchema>;

// Grading schema - output from grader agent
export const gradingSchema = z.object({
    points: z
        .number()
        .int()
        .min(0)
        .max(2)
        .describe("Points awarded: 0, 1, or 2"),
    feedback: z
        .string()
        .describe("Feedback explaining the grade with correct answer"),
});

export type Grading = z.infer<typeof gradingSchema>;

// Course request schema - input for course creation
export const courseRequestSchema = z.object({
    query: z.string().describe("What the user wants to learn"),
    timeHours: z
        .number()
        .min(0)
        .max(30)
        .describe("Total course duration in hours"),
    difficulty: z
        .enum(["easy", "medium", "hard"])
        .describe("Course difficulty level"),
    language: z
        .enum(["en", "id"])
        .describe("Course language: English or Indonesian"),
    documentIds: z
        .array(z.string())
        .optional()
        .describe("IDs of uploaded documents to use as context"),
    imageIds: z
        .array(z.string())
        .optional()
        .describe("IDs of uploaded images to use as context"),
});

export type CourseRequest = z.infer<typeof courseRequestSchema>;

// Full course schema - complete course output
export const fullCourseSchema = z.object({
    info: courseInfoSchema,
    chapters: z.array(
        z.object({
            chapter: chapterSchema,
            content: chapterContentSchema,
            quiz: quizSchema,
            imageUrl: z.string().optional(),
        }),
    ),
});

export type FullCourse = z.infer<typeof fullCourseSchema>;
